### ISSUE TITLE
Use hibernate?

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/boulder-dash#1]

**Comment by moshewe** [comment]
I know I'm a little out of touch, but why exactly?
I'll use this question to better understand the codebase.

**Comment by ColinLeverger** [comment]
Basically we had a course today with our java teatcher and he was talking about this thing; I don't think that it is a good idea because we do not need a database for this project!

**Comment by moshewe** [comment]
Whatever database we need we can do with anything that stores Java natively.
I come from an enterprise background and I've worked with Hibernate, it's
not that great of a thing even when you really do need it!

Where are you studying?

**Comment by ColinLeverger** [comment]
We are actually in the north west of France, in Lannion city, in an engineering school called ENSSAT :)

**Comment by moshewe** [comment]
Breton! Love the music from there!
The only French institute I've every had anything to do with is INRIA

**Comment by ColinLeverger** [comment]
I never heard about this one! Yay if you enjoy gigs & beer you definitely should come down here ;-)

**Comment by valeriansaliou** [comment]
Mhhh, wanted to implement Hibernate for highscore saving and restoration purposes. Just so that we could match our courses, though I think we should pick a better system for DB access.
