### ISSUE TITLE
Path for audio files in AudioLoadHelper non-relative

### ISSUE THREAD

**Issue by moshewe** [valeriansaliou/boulder-dash#17]
I'm running the game from IntelliJ and there the project working directory is different from what you guys use so it doesn't find the sound files.

I'll fix it to do a relative search for the files, relative to the location of AudioLoadHelper. That way when the game is run simply as a jar file it will still work. Working through paths doesn't work when run from within a jar file.

**Comment by valeriansaliou** [comment]
Great, didn't ship any Jar file ATM so couldn't notice that. Thx ;)

**Comment by ColinLeverger** [comment]
Orel, if you do understand where is this problem, please make a quick fix, I do not understand myself ! :-)
