### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Trilarion** [valeriansaliou/boulder-dash#35]
Hi,

Does the project has an open source license allowing sharing and mofication like GPL, MIT, BSD, ... or is it more like "all rights reserved"? If it isn't licensed like this, is such a step planned in the future?

I could not find such specific information about the license status in the code or in the issues but the project looks promising.

Thanks and kind regards.

**Comment by valeriansaliou** [comment]
Hi! You may go ahead, it's in the public domain.

**Comment by Trilarion** [comment]
Thanks. That is very generous. Unfortunately, public domain has some legal problems (in some parts of the world the concept of public domain is not known). I would be more comfortable using a widespread, very permissive license like the MIT license instead.

Is it okay, if I fork this repository and add the MIT license?

**Comment by Trilarion** [comment]
Or if you also like the MIT license and want to consider adding it here that would be fine for me too.

**Comment by valeriansaliou** [comment]
Yes sure it's okay. This repo. won't be updated anyway, so you're free to fork it & add that license.

**Comment by valeriansaliou** [comment]
Just added the MIT license `LICENSE` file in this repository. Thanks! You're free to fork now :)

**Comment by Trilarion** [comment]
Thanks. Very nice.
